### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Dranos-Nupper** [Hyakkimaru/LegionFiles#1]
I am thankfull that your working on this...but some textures are missing :+1:

**Comment by Hyakkimaru** [comment]
Don't hesitate to help if you think something is missing, we are two on it and it'll need a lot of work !

**Comment by Dranos-Nupper** [comment]
i will do what i can to help :)

**Comment by Dranos-Nupper** [comment]
Found theses two Files:
Creature\DHFemaleTank\NightElf_Female_DH_Havoc_hair.blp
Creature\NightborneMale\Nightborne_Male_Armor.blp

**Comment by Hyakkimaru** [comment]
Thank you Nupper, I just added them :) !
